### ISSUE TITLE
task gets skipped

### ISSUE THREAD

**Issue by ghost** [reyvonger/rikani_radio#10]
[WARNING]: Found both group and host with same name: localhost

PLAY [localhost] **********************************************************************

TASK [Gathering Facts] ****************************************************************
ok: [localhost]

TASK [radio : Install dependences] ****************************************************
ok: [localhost]

TASK [radio : Add gpg docker] *********************************************************
ok: [localhost]

TASK [radio : Add repository] *********************************************************
ok: [localhost]

TASK [radio : Install docker] *********************************************************
ok: [localhost]

TASK [radio : Install dependences in pip] *********************************************
ok: [localhost]

TASK [radio : enable docker] **********************************************************
ok: [localhost]

TASK [radio : upgrade ubuntu] *********************************************************
ok: [localhost]

TASK [radio : Creates deploy dir] *****************************************************
ok: [localhost]

TASK [radio : check music.sha256] *****************************************************
ok: [localhost]

TASK [radio : create music.sha256] ****************************************************
changed: [localhost]

TASK [radio : Create a music link] ****************************************************
skipping: [localhost]

TASK [radio : Create a video link] ****************************************************
skipping: [localhost]

TASK [radio : new video source] *******************************************************
ok: [localhost]

TASK [radio : move video] *************************************************************
skipping: [localhost]

TASK [radio : create mpc alias] *******************************************************
ok: [localhost]

TASK [radio : Use sha256 to calculate checksum] ***************************************
ok: [localhost]

TASK [radio : music dir sha256] *******************************************************
ok: [localhost]

TASK [radio : read music.sha256] ******************************************************
ok: [localhost]

TASK [radio : Decode music.sha256] ****************************************************
ok: [localhost]

TASK [radio : template ffmpeg entrypoint.sh] ******************************************
ok: [localhost]

TASK [radio : template mpd entrypoint.sh] *********************************************
ok: [localhost]

TASK [radio : copy font] **************************************************************
ok: [localhost]

TASK [radio : template docker] ********************************************************
ok: [localhost]

TASK [radio : deploy] *****************************************************************
ok: [localhost]

TASK [radio : restart mpd] ************************************************************
changed: [localhost]

TASK [radio : new sha256 output] ******************************************************
changed: [localhost -> localhost]

RUNNING HANDLER [radio : restart ffmpeg] **********************************************
changed: [localhost]

PLAY RECAP ****************************************************************************
localhost                  : ok=25   changed=4    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0

**Comment by ghost** [comment]
also how you(author of this repo) said in another issue that the stream is gonna start soon, it didnt.

**Comment by reyvonger** [comment]
skipped tasks is normal

now there is a problem with some video formats, maybe you have encountered it, I will release a patch in the coming days
