### ISSUE TITLE
Как зациклить видео?

### ISSUE THREAD

**Issue by cybersecnn** [reyvonger/rikani_radio#4]
Привет парни. Спасибо за приложение) Проблемка только одна -вставил видео длиной 8 минут. Как сделать так, чтобы оно было бесконечным?

**Comment by reyvonger** [comment]
шалом, по умолчанию за итератор берется музыка, которая бесконечна, а видео крутится в цикле. т.е. видео и так идет бесконечно :)

**Comment by cybersecnn** [comment]
Оперативно однако) Благодарю. Разобрался. При стандартных настройках ffmpeg проц на 250-300% работал. От этого трансляция отрубалась через 5-7 минут. Уменьшил битрейт и все заработало. Друже, еще вопрос, если можно)
Трансляция запущена, все работает. Но если я захочу увеличить плейлист музыки, можно как-то его обновить без перезапуска трансляции?

**Comment by reyvonger** [comment]
да, просто вбивание команды еще раз со всеми настройками (-e key=value -e key=value), переиндексация выполняется только если новые треки добавлены в каталог с музыкой
