### ISSUE TITLE
Завершение трансляции

### ISSUE THREAD

**Issue by RitzAtemo** [reyvonger/rikani_radio#6]
Такой вопрос - можно ли остановить трансляцию непосредственно с виртуальной машины, а не через "Завершить трансляцию" на YouTube? Потому что когда я останавливал трансляцию вторым способом - трансляция просто создавалась новая, поток продолжал идти. Можно как-то контролировать этот процесс?

**Comment by reyvonger** [comment]
День добрый, в целом да, можно делать - docker stop ffmpeg - это остановит трансляцию
